= Remote Controller
ifndef::imagesdir[:imagesdir: images]
:sourcedir:
:icons:
:sectnums:
:toc:

Der Remote Controller ist die Fernsteuerung und kann per USB mit dem Handy verbunden werden. Das Handy kann mit der Drohne kommunizieren oder den Stream der Kamera erhalten. +
Manche Geräte können miteinander zu master-slave Beziehungen verknüpft werden, wobei der Eine die Steuerelemente betätigt und der Andere die Kamera steuert.

== Control Input
Die Steuerelemente können auf den beiden Steuerknüppeln verschieden angeordnet sein.

== Control Sticks
Es gibt zwei Steuerknüppel die verschiedene Modi haben können.

.Standardmodus
[width="100%",options="header,footer"]
|====================
| links || rechts |
|horizontal  |Gas, Bremse  |horizontal  |y-Achse
|vertikal  |z-Achse  |vertikal  |x-Achse
|====================

=== Flight Mode
Die verschiedenen Modi können die Sensorik überschreiben.
Es gibt 5 modi (P, T, A, F, S), wobei jede drohne 2-3 davon hat.

==== P-MODE(Positioning):
In dem Modus verwendet die Drohne alle Hilfsmittel die vorhanden sind(GPS, Vision Positioning System, Obstacle Avoidance System). +
Es erlaubt erweiterte Einstellungen wie Missions, Virtual Sticks and Intelligent Orientation Control, wenn die Drohne keinen F-Mode hat.

==== T-MODE(Tripod):
Intelligent Flight ist nicht vorhanden. Hinzu ist die Geschwindigkeit, Beschleunigung, Bremskraft reduziert auf 1m/s.

==== A-MODE(Attribute):
Außer dem Barometer werden keine positionsbezogenen Sensoren verwendet.

==== F-MODE(Function):
Der Modus hat die gleichen Eigenschaften wie im P-Mode allerdings ist dieser höher gewertet.

==== S-MODE(Sport):
Alle positionsbezogenen Hilfen werden verwendet. Zusätzlich erhöhen sich auch die Flugeigenschaften und die Geschwindigkeit wird auf 20m/s erhöht.


=== Master / Slave Controll
Ein Gerät ist im Master Zustand und kontrolliert die Drohne. +
Das Andere ist im Slave Zustand und erhält das Videomaterial. Außerdem kommuniziert es mit dem Master Control, um Gimbal und Kamerazugang zu erhalten +
Beide Geräte müssen per DJI Go oder DJI Mobile SDK APi miteinander verbunden sein.

=== Custom Buttons
Es sind 2 Buttons auf der Rückseite die nur per Mobile SDK verfügbar sind. Auf die Buttons kann jederzeit zugegriffen werden.

=== Mobile Remote Controller
Wenn der Controller abwesend ist, erscheint auf der Mobile SDK die Steuerung. +
Allerdings ist dieses Feature nur bei der MAVIC PRO oder der SPARK vorhanden.
